import subprocess
import os
import uuid

def convert_pptx_to_pdf(input_file: str, output_dir: str) -> str:
    """
    Convert a PowerPoint (.pptx) file to PDF using LibreOffice (soffice).
    
    Args:
        input_file (str): Path to the input .pptx file.
        output_dir (str): Directory where the output PDF should be saved.

    Returns:
        str: Path to the converted PDF file.
    """
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Create a unique filename for the output PDF
    output_file = os.path.join(output_dir, f"{uuid.uuid4()}.pdf")

    # Run LibreOffice in headless mode
    try:
        result = subprocess.run(
            [
                "soffice",
                "--headless",
                "--convert-to",
                "pdf:writer_pdf_Export",
                "--outdir",
                output_dir,
                input_file,
            ],
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Conversion failed: {e.stderr or e.stdout}")

    # LibreOffice saves with the same base name, so we rename it to our unique file
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    generated_file = os.path.join(output_dir, f"{base_name}.pdf")

    if os.path.exists(generated_file):
        os.rename(generated_file, output_file)
    else:
        raise FileNotFoundError("PDF was not generated by LibreOffice")

    return output_file
